#########################################################################
# Title:            Cloudbox Community: transmissionvpn                 #
# Author(s):        Tarek, im-mortal                                    #
# URL:              https://github.com/Cloudbox/Community               #
# Docker Image(s):  haugene/transmission-openvpn                        #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Setting CloudFlare DNS Record"
  include_role:
    name: cloudflare-dns
  vars:
    record: transmissionvpn
  when: cloudflare_enabled

- name: Stop and remove any existing container
  docker_container:
    name: transmissionvpn
    state: absent

- name: Create transmissionvpn directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - /opt/transmissionvpn
    - /opt/transmissionvpn/config
    - /opt/transmissionvpn/data
    - /opt/transmissionvpn/vpn

- name: Create new downloads directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }} recurse=yes"
  with_items:
    - "{{ downloads.torrents }}"
    - "{{ downloads.torrents }}/transmissionvpn"
    - "{{ downloads.torrents }}/transmissionvpn/completed"
    - "{{ downloads.torrents }}/transmissionvpn/incoming"
    - "{{ downloads.torrents }}/transmissionvpn/watched"
    - "{{ downloads.torrents }}/transmissionvpn/torrents"
  when: (torrents_downloads_path is defined)|default(false)

# https://haugene.github.io/docker-transmission-openvpn/run-container/#1_the_container_assumes_that_you_mount_a_folder_to_data
- name: Set the data_volume variable
  set_fact:
    data_volume: "{{[downloads.torrents + '/transmissionvpn:/data'] if torrents_downloads_path_is_defined else [] }}"

- name: Set default_volumes variable
  set_fact:
    default_volumes:
      - "/opt/transmissionvpn/vpn:/etc/openvpn/custom"
      - "/mnt:/mnt"
      - "/opt/transmissionvpn/config:/config"
      - "/opt/transmissionvpn/data:/data"

- name: Create and start container
  docker_container:
    name: transmissionvpn
    image: haugene/transmission-openvpn
    pull: yes
    env:
      PUID: "{{ uid }}"
      PGID: "{{ gid }}"
      VIRTUAL_HOST: "transmissionvpn.{{ user.domain }}"
      VIRTUAL_PORT: "9091"
      LETSENCRYPT_HOST: "transmissionvpn.{{ user.domain }}"
      LETSENCRYPT_EMAIL: "{{ user.email }}"
      UMASK_SET: "002"
      CREATE_TUN_DEVICE: "true"
      OPENVPN_PROVIDER: "{{ transmissionvpn.openvpn_provider|default('pia',true) }}"
      OPENVPN_USERNAME: "{{ transmissionvpn.openvpn_user|default('username',true) }}"
      OPENVPN_PASSWORD: "{{ transmissionvpn.openvpn_password|default('password',true) }}"
      OPENVPN_CONFIG: "{{ transmissionvpn.openvpn_config }}"
      TRANSMISSION_DOWNLOAD_DIR: "{{ transmissionvpn.transmission_download_dir|default('/data/completed',true) }}"
      TRANSMISSION_INCOMPLETE_DIR: "{{ transmissionvpn.transmission_incomplete_dir|default('/data/incomplete',true) }}"
      TRANSMISSION_WATCH_DIR: "{{ transmissionvpn.transmission_watch_dir|default('/data/watch',true) }}"
      TRANSMISSION_RPC_AUTHENTICATION_REQUIRED: "{{ transmissionvpn.transmission_rpc_authentication_required|default('false',true) }}"
      TRANSMISSION_RPC_USERNAME: "{{ transmissionvpn.transmission_rpc_username|default('username',true) }}"
      TRANSMISSION_RPC_PASSWORD: "{{ transmissionvpn.transmission_rpc_password|default('password',true) }}"
      TRANSMISSION_WEB_UI: "{{ transmissionvpn.transmission_web_ui|default('flood-for-transmission',true) }}"
      WEBPROXY_ENABLED: "{{ transmissionvpn.webproxy_enabled|default('true',true) }}"
      WEBPROXY_PORT: "{{ transmissionvpn.webproxy_port|default('8888',true) }}"
      WEBPROXY_USERNAME: "{{ transmissionvpn.webproxy_username|default('username',true) }}"
      WEBPROXY_PASSWORD: "{{ transmissionvpn.webproxy_password|default('password',true) }}"
      TRANSMISSION_ALT_SPEED_DOWN: "30"
      TRANSMISSION_RATIO_LIMIT: "0"
      TRANSMISSION_RATIO_LIMIT_ENABLED: "true"
      TRANSMISSION_WATCH_DIR_ENABLED: "false"
      TZ: "{{ tz }}"
    volumes: "{{ default_volumes + torrents_downloads_path + data_volume|default([]) }}"
    dns_servers: 8.8.8.8
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
    capabilities:
      - NET_ADMIN
    networks:
      - name: cloudbox
        aliases:
          - transmissionvpn
    purge_networks: yes
    restart_policy: unless-stopped
    state: started
